### ISSUE TITLE
[Suggestion] Zero Sum Rewards

### ISSUE THREAD

**Issue by Passerby** [kimbring2/MOBA_RL#6]
Good job! Did you complete this project on your own?
I believe that converting this into a self-play zero-sum game would yield excellent results. and remove derk.

**Comment by kimbring2** [comment]
@Passerby Hello!! Thank for interesting to my project. 

I could implement by combining various open source project and train the 1:1 agent. 

Theoretically, it is correct to use zero-sum, but the game time is too long and there is no way to get a replay of human expert. Therefore. I had no choice but to give some an additional reward to agent when it hits, kills the enemy.
